[package]
name = "blog_os"
version = "0.1.0"
authors = ["yooml <947801604@qq.com>"]
edition = "2018"

[dependencies]
bootloader = "0.8.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
